name: Android Integration Test on macOS 13

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter 3.24.0
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          build
        key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Install Android SDK
      run: |
        brew install --cask android-sdk
        sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;default;x86_64" "emulator"
        sdkmanager --licenses
        sdkmanager --update

    - name: Create and Start AVD
      run: |
        avdmanager create avd -n test -k "system-images;android-30;default;x86_64" --force
        nohup emulator -avd test -no-audio -no-window -gpu off &

    - name: Wait for Android Emulator to Boot
      run: |
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Run Integration Tests
      run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
