name: Android Integration Test on macOS 13

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8 (Temurin)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Set up Flutter 3.24.0
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          build
        key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis  # Choose an image suitable for your app
        arch: x86_64
        profile: Nexus 6P
        script: |
          flutter pub get
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
