name: Android Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ADB_INSTALL_TIMEOUT: 10
      AVD_NAME: test
      ANDROID_SDK_ROOT: $HOME/android-sdk
      JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.24-8/x64
      PATH: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$PATH

    steps:
    - name: Install necessary tools
      run: apt-get update && apt-get install -y tar gzip

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK Command-Line Tools
      run: |
        apt-get update -qq
        apt-get install -y wget unzip
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        yes | sdkmanager --licenses
        sdkmanager --update

    - name: Install Android SDK Components
      run: |
        sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;default;x86_64" "emulator"

    - name: Create AVD
      run: |
        avdmanager create avd -n $AVD_NAME -k "system-images;android-30;default;x86_64" --force
        EMULATOR_NAME=$(emulator -list-avds | head -n 1)
        nohup emulator -avd $EMULATOR_NAME -no-window -no-audio -no-boot-anim -gpu off &

    - name: Wait for Android Emulator to boot
      run: |
        adb devices
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Integration Tests
      run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
