name: Flutter Integration Tests on macOS 13

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-test:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Debug APK
      run: flutter build apk --debug

    - name: Run Android Emulator and Debug APK
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6P
        avd-name: test
        emulator-options: "-no-window -no-audio -no-boot-anim"
        script: |
          flutter test
          flutter build apk --debug
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; sleep 10'
          for i in {1..3}; do adb install build/app/outputs/flutter-apk/app-debug.apk && break; sleep 10; done
          flutter test integration_test/app_test.dart

  ios-test:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install Dependencies
      run: flutter pub get

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Build iOS App
      run: flutter build ios --debug --no-codesign

    - name: Run iOS Simulator and Tests
      run: |
        xcrun simctl boot "iPhone 12 (14.5)"
        xcrun simctl install booted build/ios/iphonesimulator/Runner.app
        xcrun simctl launch booted com.example.testing_demo
        flutter test integration_test/app_test.dart
