name: Android Integration Test on macOS 13

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  emulator-test:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6P
        avd-name: test
        emulator-options: "-no-window -no-audio -no-boot-anim"
        script: adb devices

    - name: Wait for Emulator to Boot
      run: |
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
        adb shell getprop sys.boot_completed

    - name: Run Integration Tests
      run: ./gradlew app:connectedAndroidTest -Ptarget=`pwd`/integration_test/app_test.dart
