name: Android Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        options: --privileged
        image: cirrusci/flutter:latest

    env:
      ADB_INSTALL_TIMEOUT: 10
      AVD_NAME: test
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Set up Android emulator
      run: |
        sudo apt-get update
        sudo apt-get install -y lib32stdc++6 qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
        sudo adduser $USER libvirt
        sudo adduser $USER kvm
        sudo apt-get install -y adb
        sudo apt-get install -y android-tools-adb android-tools-fastboot
        sdkmanager --install 'system-images;android-30;default;x86_64'
        sdkmanager --install 'platforms;android-30'
        sdkmanager --install 'platform-tools'
        sdkmanager --install 'emulator'
        sdkmanager --licenses
        avdmanager create avd -n $AVD_NAME -k 'system-images;android-30;default;x86_64' --force
        EMULATOR_NAME=$(emulator -list-avds | head -n 1)
        nohup emulator -avd $EMULATOR_NAME -no-window -no-audio -no-boot-anim -gpu off &

    - name: Wait for Android Emulator to boot
      run: |
        adb devices
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Run Integration Tests
      run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
